[app]
name = "DPSK"
version = "1.0.0"
port = ":8080"
env = "dev" # prod/dev/test

[log]
level = "info" # debug/info/warn/error/fatal
path = "."
console = true
file = true
max_size = 100 # MB
max_backups = 7
max_age = 30 # days
compress = true

[database]
host = "47.109.106.188"
port = 3306
user = "miajio"
password = "C3p0&MySql"
name = "dpsk"
max_idle_conns = 10
max_open_conns = 100
conn_max_lifetime = "5m"

[redis]
addr = "localhost:6379"
password = ""
db = 0
pool_size = 20

[jwt]
prefix = "Authorization:"
expires = "24h"
